name: Build
on:
  workflow_dispatch:
  push:
jobs:
  job:
    name: Build 🔧
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: pnpm/action-setup@master
      with:
        version: latest
    - uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm build
    - uses: corcc/publish@node
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TZ: 'Asia/Tokyo'
        TASK_NAME: 🔧
