name: Build and Test
on: 
  workflow_dispatch:
  push:
jobs:
  job:
    name: Build 🔧
    runs-on: ubuntu-latest
    strategy:
     matrix:
      yarn: 
        - 'rm -rf dist build && yarn build:tsc:noargs'
        - 'yarn test:request'
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - uses: actions/checkout@master
    - id: node-cache
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ github.repository }}-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ github.repository }}-node-modules-
    - run: |
       yarn cache clean
       yarn install
    - run: |
       ${{ matrix.yarn }}
    - uses: corcc/publish@master
      if: ${{ contains(matrix.yarn, 'build') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TASK_NAME: 🔧
        TIMEZONE: 'Asia/Tokyo'
